pizza_mama/main/urls.py
from django.urls import path
from .import views

app_name = 'main'

urlpatterns = [
    path('', views.index, name='index'),
]

pizza_mama/menu/urls.py
from django.urls import path
from .import views

app_name = 'menu'

urlpatterns = [
    path('', views.index, name='index'),
]

pizza_mama/pizza_mama/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('menu/', include('menu.urls')),
    path('', include('main.urls')),
]

pizza_mama/main/models.py
from django.db import models

# Create your models here.

pizza_mama/menu/models.py
from django.db import models

class Pizza(models.Model):
    name = models.CharField(max_length=200)
    ingredients = models.CharField(max_length=400)
    price = models.FloatField(default=0.0)
    vegetarian = models.BooleanField(default=False)

    def __str__(self):
        return self.name

pizza_mama/main/views.py
from django.shortcuts import render
from django.http import HttpResponse

def index(request):
    return render(request, 'main/index.html')

pizza_mama/menu/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .models import Pizza

def index(request):
    # pizzas = Pizza.objects.all()
    # pizzas_names_and_prices = [f"{i}. {pizza.name.capitalize()} -- {pizza.price} €" for i, pizza in enumerate(pizzas, start=1)]
    # return HttpResponse("Les pizzas disponibles sont :</br></br>" + "</br>".join(pizzas_names_and_prices))
    pizzas = Pizza.objects.all().order_by('price')
    return render(request, 'menu/index.html', {'pizzas': pizzas})

pizza_mama/main/templates/main/index.html
{% load static %}

<html lang="fr">
<head>
    <meta charset="UTF-8">
    <title>Pizza mama</title>
    <link rel="stylesheet" href="{% static 'main/style.css' %}">
</head>
<body>
    <div class="centered">
        <img id="main_logo" src="{% static 'main/images/main_logo.png' %}">
        <a href="{% url 'menu:index' %}">Menu</a>
    </div>
</body>
</html>

pizza_mama/menu/templates/menu/index.html
{% load static %}

<html lang="fr">
<head>
    <meta charset="UTF-8">
    <title>Menu des pizzas</title>
    <link rel="stylesheet" href="{% static 'menu/style.css' %}">
</head>
<body>
    <a href="{% url 'main:index' %}"><img id="small_logo" src="{% static 'menu/images/small_logo.png' %}" alt="logo"></a>
    
    <div class="menu_title">
        <h1>Les pizzas</h1>
    </div>

    <div class="menu_list">
        {% for pizza in pizzas %}
            <div class="menu_list_item">
                <span class="menu_list_title">{{pizza.name|title}}</span>
                <span class="menu_list_price">{{pizza.price|floatformat:2}} €</span>
                <span class="menu_list_ingredients">{{pizza.ingredients}}</span>
                {% if pizza.vegetarian %}
                    <span class="menu_list_vegetarian">VEGETARIENNE</span>
                {% endif %}
            </div>
        {% endfor %}
    </div>
</body>
</html>